### PR TITLE
Major overhaul

### PR DESCRIPTION
**Pull request by larzw**
* Created standard GitHub project stucture. Included in this was an MIT License file
with a copyright of Codecov and contributors.
* Switched to using xUnit.
* Cleaned up code.
* Cleaned up readme.
* Fixed solution name.
* Added Codecov badge.
* Added AppVeyor badge.
* Fixed OpenCover filters.

### CODE REVIEW

**Comment by larzw** [comment]
@stevepeak,

Your suggestions and comments especially on the README file would be appreciated...Thanks!

**Comment by larzw** [comment]
I think the OpenCover filters where wrong/missing too, which is why the coverage changed so much.

**Comment by larzw** [comment]
@stevepeak 

The example C# project [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) is now using Codecov-exe. I've updated the overhauled readme with that info. Would you mind taking a look at this PR when you get a chance? Thanks!

**Comment by stevepeak** [comment]
Thank you @larzw 👍

**Pull request merged**
