### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TomPed**
We want a more standard style for the Codecov example READMD.mds. I've added and moved around a few things. @larzw it looks like you've done some work on this. Would you mind reviewing the changes?

### CODE REVIEW

**Comment by larzw** [comment]
LGTM 👍

**Comment by TomPed** [comment]
Cool, @larzw can you merge?

**Comment by larzw** [comment]
@stevepeak can you merge? I don't have the correct rights anymore.

**Comment by raschmitt** [comment]
@TomPed, it seems that this merge got "lost".

Still, I tried to follow your instructions regarding `.Net Core` to setup continuous integration trough Github actions, and even though all my `.csproj` files contain the `<DebugType>full</DebugType>` tag when I try to generate my reports, no report gets generated, and I get the following error message:

```
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```

Could you provide me some assistance on what am I'm doing wrong?

My repository: https://github.com/raschmitt/date-override
Action I'm trying to run: https://github.com/raschmitt/date-override/blob/master/.github/workflows/dotnet-core.yml
Action results: https://github.com/raschmitt/date-override/runs/886072938?check_suite_focus=true

**Comment by thomasrockhu** [comment]
Closing in favor of https://github.com/codecov/example-csharp/pull/30

**Pull request closed without merging**
